# Generated by Django 5.1.5 on 2025-02-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepressionRecord",
        ),
        migrations.DeleteModel(
            name="DiabetesRecord",
        ),
        migrations.DeleteModel(
            name="StrokeRecord",
        ),
    ]
