# Generated by Django 5.1.5 on 2025-02-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diabetesrecord",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="strokerecord",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="DepressionRecord",
        ),
        migrations.DeleteModel(
            name="DiabetesRecord",
        ),
        migrations.DeleteModel(
            name="StrokeRecord",
        ),
    ]
